# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('edu_form', models.CharField(choices=[('full-fime', 'Очная'), ('part-fime', 'Заочная')], max_length=255)),
                ('number', models.IntegerField()),
                ('course', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('edu_level', models.CharField(choices=[('low', 'Низший'), ('mid', 'Средний'), ('high', 'Высший')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('patronymic_name', models.CharField(max_length=255)),
                ('date_birth', models.DateField()),
                ('course', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Group')),
            ],
        ),
    ]
