# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20160825_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('title', 'course')},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('last_name', 'first_name')},
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.Group'),
        ),
    ]
